### ISSUE TITLE
Is there anyway to decrypt LoadData.plist

### ISSUE THREAD

**Issue by WEGFan** [Cos8o/GDCrypto#6]

**Comment by Cos8o** [comment]
no, havent looked it yet, will do ;)

**Comment by WEGFan** [comment]
Python script here
```python
import base64
import gzip
import itertools
import re

def xor_cipher(string: bytes, key: bytes) -> bytes:
    return bytes(x ^ y for x, y in zip(string, itertools.cycle(key)))

def decrypt_load_data(string: str) -> str:
    data = string.encode('utf-8')
    data = base64.urlsafe_b64decode(data)
    data = xor_cipher(data, b'48291')
    data = base64.urlsafe_b64decode(data)
    data = gzip.decompress(data)
    return data.decode('utf-8')

with open('./LoadData.plist', 'r', encoding='utf-8') as f:
    data = f.read()

# extract the actual string
data = re.search(r'^\t<string>(.*)</string>$', data, re.MULTILINE).group(1)
decrypted = decrypt_load_data(data)

with open('./LoadData.txt', 'w', encoding='utf-8') as f:
    f.write(decrypted)
```
After decryption, the file is like `11930493,10,11882052,5,11304531,8,11882052,5,11304531,8,11984627,6,11984104,4,11983287,6` and it's actually `levelId,stars,levelId,stars, ...`.
The decryption function is called `LevelTools::createStarLevelDict` in Android x86 version of the game, and it's used in `GameManager::recountUserStats` which is called by `GJAccountManager::onSyncAccountCompleted`, so maybe it's used for reset the level's stars after loading cloud save?
